name: fc_file_picker_util
description: "File pickers based on file_selector."
version: 0.7.0
homepage: https://github.com/flutter-cavalry/fc_file_picker_util

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

platforms:
  android:
  ios:
  macos:
  windows:

dependencies:
  file_selector: ^1.0.1
  flutter:
    sdk: flutter
  ios_document_picker: ^0.2.0
  macos_file_picker: ^0.3.0
  saf_util: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
