name: fast_file_picker
description: "Fast file pickers for Flutter"
version: 0.2.0
homepage: https://github.com/flutter-cavalry/fast_file_picker

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

platforms:
  android:
  ios:
  macos:
  windows:
  linux:

dependencies:
  file_selector: ^1.0.1
  flutter:
    sdk: flutter
  ios_document_picker: ^0.3.0
  macos_file_picker: ^0.4.0
  path: ^1.9.0
  saf_util: ^0.6.1
  accessing_security_scoped_resource: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mgenware_dart_lints: ^7.0.0
