name: fc_file_picker_util
description: "File pickers based on file_selector."
version: 0.4.0
homepage: https://github.com/flutter-cavalry/fc_file_picker_util

environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=3.7.0"

platforms:
  android:
  ios:
  macos:
  windows:

dependencies:
  file_picker: ^8.0.3
  file_selector: ^1.0.1
  flutter:
    sdk: flutter
  ios_document_picker: ^0.0.1
  macos_file_picker: ^0.3.0

  saf_util:
    git:
      url: https://github.com/flutter-cavalry/saf_util.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
